export enum NotificationType {
  FRIEND_REQUEST_SENT = 'FRIEND_REQUEST_SENT',
  FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED',
  POST_REACTED = 'POST_REACTED',
  POST_COMMENTED = 'POST_COMMENTED',
  COMMENT_REACTED = 'COMMENT_REACTED',
  COMMENT_REPLY_CREATED = 'COMMENT_REPLY_CREATED',
  REPORT_RESULT = 'REPORT_RESULT',
  CONTENT_REMOVED_VIOLATION = 'CONTENT_REMOVED_VIOLATION',
  CONTENT_RESTORED = 'CONTENT_RESTORED',
}
