export enum NotificationType {
  FRIEND_REQUEST_SENT = 'FRIEND_REQUEST_SENT',
  FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED',
  POST_LIKED = 'POST_LIKED',
  POST_COMMENTED = 'POST_COMMENTED',
  COMMENT_LIKED = 'COMMENT_LIKED',
  COMMENT_REPLY_CREATED = 'COMMENT_REPLY_CREATED',
}
